PROGRAM VariablesValues(INPUT, OUTPUT);
USES DOS;
BEGIN
  WRITELN;
  WRITELN('REQUEST METHOD: ', GetEnv('REQUEST_METHOD'));
  WRITELN('QUERY STRING: ', GetEnv('QUERY_STRING'));
  WRITELN('CONTENT LENGTH: ', GetEnv('CONTENT_LENGTH'));
  WRITELN('HTTP USER AGENT: ', GetEnv('HTTP_USER_AGENT'));
  WRITELN('HTTP HOST: ', GetEnv('HTTP_HOST'))
END.